name: arisee
channels:
  - conda-forge
dependencies:
  - python = 3.7
  - scipy >= 1.0.0
  - numpy >= 1.11.0
  - matplotlib >= 1.5.1
  - flake8
  - sphinx
  - cython
  - sphinxcontrib-bibtex
  - pint
