name: arisee
channels:
  - conda-forge
dependencies:
  - python == 3.7
  - scipy == 1.3.1
  - numpy == 1.17.3
  - matplotlib == 3.1.2
  - flake8
  - sphinx
  - cython
  - sphinxcontrib-bibtex
  - pint
  - cvxopt
